name: Cloud Custodian

on:
  push:
    branches:
      - main

jobs:
  run_custodian:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Cloud Custodian
        run: pip install c7n

      - name: Execute Cloud Custodian
        run: custodian run --config custodian.yml
